C:\Users\jawk\OneDrive\Documents\GitHub\we-re-board-backend>cd tests

C:\Users\jawk\OneDrive\Documents\GitHub\we-re-board-backend\tests>lettuce
c:\python27\lib\site-packages\fuzzywuzzy\fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')

Feature: Register a user                                                                                  # \features\ID001_Register_New_User.feature:1
  As an upcoming user of the "We're Board" app, I would like to register to the app                       # \features\ID001_Register_New_User.feature:3
  so that I can use the application.                                                                      # \features\ID001_Register_New_User.feature:4

  Scenario: Register to the app - Normal Flow                                                             # \features\ID001_Register_New_User.feature:6
    Given I am browsing the login page                                                                    # \features\st    Given I am browsing the login page                                                                    # \features\steps.py:12
    And I clicked on the register button                                                                  # \features\st    And I clicked on the register button                                                                  # \features\steps.py:15
    When I fill in these information to my profile:                                                       # \features\steps.py:18
      | Name  | Surname  | Username | Password | Password confirmation | email            | Phone Number | Description |
      | Amine | Alikacem | Amine    | bla3Bla; | bla3Bla;              | amine@outlook.ca | 15143334444  | blabla      |
c:\python27\lib\site-packages\urllib3\util\ssl_.py:380: SNIMissingWarning: An HTTPS request has been made, but the SNI (Server Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  SNIMissingWarning,
c:\python27\lib\site-packages\urllib3\util\ssl_.py:139: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgr    When I fill in these information to my profile:                                                       # \features\steps.py:18.html#ssl-warnings
      | Name  | Surname  | Username | Password | Password confirmation | email            | Phone Number | Description |
      | Amine | Alikacem | Amine    | bla3Bla; | bla3Bla;              | amine@outlook.ca | 15143334444  | blabla      |
    Then the system should send me an email                                                               # \features\st    Then the system should send me an email                                                               # \features\steps.py:36
    And I should now be able to sign in to the app                                                        # \features\st    And I should now be able to sign in to the app                                                        # \features\steps.py:40

  Scenario: Register to the app with a password that doesn't respect the format - Error flow              # \features\ID001_Register_New_User.feature:17
    Given I am browsing the login page                                                                    # \features\st    Given I am browsing the login page                                                                    # \features\steps.py:12
    And I clicked on the register button                                                                  # \features\st    And I clicked on the register button                                                                  # \features\steps.py:15
    When I fill in these information to my profile:                                                       # \features\steps.py:18
      | Name  | Surname  | Username | Password | Password confirmation | email            | Phone Number | Description |
      | Amine | Alikacem | Amine    | bla      | bla                   | amine@outlook.ca | 15143334444  | blabla      |
c:\python27\lib\site-packages\urllib3\util\ssl_.py:139: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgr    When I fill in these information to my profile:                                                       # \features\steps.py:18.html#ssl-warnings
      | Name  | Surname  | Username | Password | Password confirmation | email            | Phone Number | Description |
      | Amine | Alikacem | Amine    | bla      | bla                   | amine@outlook.ca | 15143334444  | blabla      |
    And My password doesn't respect the format                                                            # \features\st    And My password doesn't respect the format                                                            # \features\steps.py:60
    Then the system should display an error message                                                       # \features\st    Then the system should display an error message                                                       # \features\steps.py:64

  Scenario: Register to the app with a password and a password confirmation that don't match - Error flow # \features\ID001_Register_New_User.feature:28
    Given I am browsing the login page                                                                    # \features\st    Given I am browsing the login page                                                                    # \features\steps.py:12
    And I clicked on the register button                                                                  # \features\st    And I clicked on the register button                                                                  # \features\steps.py:15
    When I fill in these information to my profile:                                                       # \features\steps.py:18
      | Name  | Surname  | Username | Password | Password confirmation | email            | Phone Number | Description |
      | Amine | Alikacem | Amine    | bla3Bla; | bla444Bla;            | amine@outlook.ca | 15143334444  | blabla      |
c:\python27\lib\site-packages\urllib3\util\ssl_.py:139: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgr    When I fill in these information to my profile:                                                       # \features\steps.py:18.html#ssl-warnings
      | Name  | Surname  | Username | Password | Password confirmation | email            | Phone Number | Description |
      | Amine | Alikacem | Amine    | bla3Bla; | bla444Bla;            | amine@outlook.ca | 15143334444  | blabla      |
    Then the system should display an error message                                                       # \features\st    Then the system should display an error message                                                       # \features\steps.py:64

  Scenario: Register to the app with a username that already exists - Error flow                          # \features\ID001_Register_New_User.feature:39
    Given I am browsing the login page                                                                    # \features\st    Given I am browsing the login page                                                                    # \features\steps.py:12
    And I clicked on the register button                                                                  # \features\st    And I clicked on the register button                                                                  # \features\steps.py:15
    When I fill in these information to my profile:                                                       # \features\steps.py:18
      | Name  | Surname  | Username | Password | Password confirmation | email            | Phone Number | Description |
      | Amine | Alikacem | Jack     | bla3Bla; | bla3Bla;              | amine@outlook.ca | 15143334444  | blabla      |
c:\python27\lib\site-packages\urllib3\util\ssl_.py:139: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgr    When I fill in these information to my profile:                                                       # \features\steps.py:18.html#ssl-warnings
      | Name  | Surname  | Username | Password | Password confirmation | email            | Phone Number | Description |
      | Amine | Alikacem | Jack     | bla3Bla; | bla3Bla;              | amine@outlook.ca | 15143334444  | blabla      |
    And the username 'Jack' is already used                                                               # \features\st    And the username 'Jack' is already used                                                               # \features\steps.py:72
    Then the system should display an error message                                                       # \features\st    Then the system should display an error message                                                       # \features\steps.py:64

  Scenario: Register to the app with an email that is not valid                                           # \features\ID001_Register_New_User.feature:50
    Given I am browsing the login page                                                                    # \features\st    Given I am browsing the login page                                                                    # \features\steps.py:12
    And I clicked on the register button                                                                  # \features\st    And I clicked on the register button                                                                  # \features\steps.py:15
    But the email is already used                                                                         # \features\st    But the email is already used                                                                         # \features\steps.py:68
    When I fill in these information to my profile:                                                       # \features\steps.py:18
      | Name  | Surname  | Username | Password | Password confirmation | email | Phone Number | Description |
      | Amine | Alikacem | Amine    | bla3Bla; | bla3Bla;              | email | 15143334444  | blabla      |
c:\python27\lib\site-packages\urllib3\util\ssl_.py:139: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgr    When I fill in these information to my profile:                                                       # \features\steps.py:18.html#ssl-warnings
      | Name  | Surname  | Username | Password | Password confirmation | email | Phone Number | Description |
      | Amine | Alikacem | Amine    | bla3Bla; | bla3Bla;              | email | 15143334444  | blabla      |
    Then the system should display an error message                                                       # \features\st    Then the system should display an error message                                                       # \features\steps.py:64

Feature: Login to the app                                                                                    # \features\ID002_Login.feature:2
  As a registered user of the "We're Board" app, I would like to login to the app                            # \features\ID002_Login.feature:4
  so that I can use the application.                                                                         # \features\ID002_Login.feature:5

  Scenario: Login to the app (Normal Flow)                                                                   # \features\ID002_Login.feature:7
    Given I am already registered to the application with id = 301                                           # \features    Given I am already registered to the application with id = 301                                           # \features\steps.py:77
    When I login to the application with email = "login@email.ca" and password = "bla3Bla$"                  # \features\steps.py:85
c:\python27\lib\site-packages\urllib3\util\ssl_.py:139: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
    When I login to the application with email = "login@email.ca" and password = "bla3Bla$"                  # \features\steps.py:85
    Then the system logs me in and displays a confirmation message                                           # \features    Then the system logs me in and displays a confirmation message                                           # \features\steps.py:95

  Scenario: Login to the app with an email that hasn't been registered (Error Flow)                          # \features\ID002_Login.feature:13
    Given I am not yet registered to the application                                                         # \features    Given I am not yet registered to the application                                                         # \features\steps.py:81
    When I login to the application with email = "notRegistered@outlook.ca" and password = "bla3Bla;"        # \features\steps.py:85
c:\python27\lib\site-packages\urllib3\util\ssl_.py:139: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
    When I login to the application with email = "notRegistered@outlook.ca" and password = "bla3Bla;"        # \features\steps.py:85
    Then the system does not log me in and displays a "Not found" error message                              # \features    Then the system does not log me in and displays a "Not found" error message                              # \features\steps.py:102

  Scenario: Login to the app with an incorrect password (Error Flow)                                         # \features\ID002_Login.feature:19
    Given I am already registered to the application with id = 301                                           # \features    Given I am already registered to the application with id = 301                                           # \features\steps.py:77
    When I login to the application with email = "login@email.ca" and password = "bla4Pla$"                  # \features\steps.py:85
c:\python27\lib\site-packages\urllib3\util\ssl_.py:139: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
    When I login to the application with email = "login@email.ca" and password = "bla4Pla$"                  # \features\steps.py:85
    Then the system does not log me in and displays a "Invalid Credentials. Please try again." error message # \features    Then the system does not log me in and displays a "Invalid Credentials. Please try again." error message # \features\steps.py:102

Feature: Logout of the app                                                         # \features\ID003_Logout.feature:1
  As a registered user of the "We're Board" app, I would like to logout of the app # \features\ID003_Logout.feature:3
  so that I exit the application.                                                  # \features\ID003_Logout.feature:4

  Scenario: Logout to the app successfully (Normal Flow)                           # \features\ID003_Logout.feature:6
    Given I am logged in the application as an user with id = 20                   # \features\steps.py:111
    When I log out of the application                                              # \features\steps.py:115
    Then I should lose access to the application's features and redirect out       # \features\steps.py:123

Feature: View personal profile information                                                                                                             # \features\ID004_Access_My_Profile_page.feature:1
  As a user of the "We're Board" app, I would like to be able to                                                                                       # \features\ID004_Access_My_Profile_page.feature:3
  view my personal profile information so I modify it if necessary.                                                                                    # \features\ID004_Access_My_Profile_page.feature:4

  Scenario: View personal profile successfully (Normal Flow)                                                                                           # \features\ID004_Access_My_Profile_page.feature:6
    Given I am logged in as an user with id = 20                                                                            Given I am logged in as an user with id = 20                                                                                                       # \features\steps.py:130
    When I view my profile                                                                                                  When I view my profile                                                                                                                             # \features\steps.py:139
    Then the system displays the following:                                                                                                            # \features\steps.py:147
      | ID | Name    | Email             | Description | Password                                                           Then the system displays the following:                                                                                                            # \features\steps.py:147| pbkdf2:sha256:150000$Yulbep3A$5200882852aed7add39d11cdcb0b7fb08
      | ID | Name    | Email             | Description | Password                                                                                       |
      | 20 | jackson | jackson@gmail.com | I like cake | pbkdf2:sha256:150000$Yulbep3A$5200882852aed7add39d11cdcb0b7fb082345653605ef0a1295a63856b3dee5c |

  Scenario: View personal profile as a deleted user (Error Flow)                                                                                       # \features\ID004_Access_My_Profile_page.feature:13
    Given I am logged in as an user with id = 20                                                                            Given I am logged in as an user with id = 20                                                                                                       # \features\steps.py:130
    But my account does not exist                                                                                           But my account does not exist                                                                                                                      # \features\steps.py:134
    When I view my profile                                                                                                  When I view my profile                                                                                                                             # \features\steps.py:139
    Then the system displays an "Not found" error message                                                                   Then the system displays an "Not found" error message                                                                                              # \features\steps.py:165

Feature: Modify personal profile information                             # \features\ID005_Modify_Personal_Profile_Information.feature:1
  As a user of the "We're Board" app, I would like to be able to         # \features\ID005_Modify_Personal_Profile_Information.feature:3
  modify my personal profile information so I can keep it accurate.      # \features\ID005_Modify_Personal_Profile_Information.feature:4

  Scenario: Changing name successfully                                   # \features\ID005_Modify_Personal_Profile_Information.feature:6
    Given I am logged in the application as an user with id = "6"        # \features\steps.py:318
    When I enter a new name "Josh"                                       # \features\steps.py:173
c:\python27\lib\site-packages\urllib3\util\ssl_.py:139: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
    When I enter a new name "Josh"                                       # \features\steps.py:173
    Then the system displays my new name on my profile page              # \features\steps.py:185
c:\python27\lib\site-packages\urllib3\util\ssl_.py:139: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
    Then the system displays my new name on my profile page              # \features\steps.py:185

  Scenario: Changing password successfully                               # \features\ID005_Modify_Personal_Profile_Information.feature:11
    Given I am logged in the application as an user with id = "6"        # \features\steps.py:318
    When I enter a new password "bla3Bla$new"                            # \features\steps.py:205
c:\python27\lib\site-packages\urllib3\util\ssl_.py:139: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
    When I enter a new password "bla3Bla$new"                            # \features\steps.py:205
    Then the system saves my new password                                # \features\steps.py:216
c:\python27\lib\site-packages\urllib3\util\ssl_.py:139: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
    Then the system saves my new password                                # \features\steps.py:216

  Scenario: Changing email to a new valid email                          # \features\ID005_Modify_Personal_Profile_Information.feature:16
    Given I am logged in the application as an user with id = "6"        # \features\steps.py:318
    When I enter a new email "newemail@email.com"                        # \features\steps.py:237
c:\python27\lib\site-packages\urllib3\util\ssl_.py:139: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
    When I enter a new email "newemail@email.com"                        # \features\steps.py:237
    Then The system saves my email                                       # \features\steps.py:248
c:\python27\lib\site-packages\urllib3\util\ssl_.py:139: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
    Then The system saves my email                                       # \features\steps.py:248

  Scenario: Changing profile description                                 # \features\ID005_Modify_Personal_Profile_Information.feature:21
    Given I am logged in the application as an user with id = "6"        # \features\steps.py:318
    When I change my profile description to "Great"                      # \features\steps.py:268
c:\python27\lib\site-packages\urllib3\util\ssl_.py:139: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
    When I change my profile description to "Great"                      # \features\steps.py:268
    Then The system saves my new profile description                     # \features\steps.py:279
c:\python27\lib\site-packages\urllib3\util\ssl_.py:139: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
    Then The system saves my new profile description                     # \features\steps.py:279

  Scenario: Changing password fails due to invalid password - Error Flow # \features\ID005_Modify_Personal_Profile_Information.feature:26
    Given I am logged in the application as an user with id = "6"        # \features\steps.py:318
    When I enter a new invalid password "badpassword"                    # \features\steps.py:298
c:\python27\lib\site-packages\urllib3\util\ssl_.py:139: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
    When I enter a new invalid password "badpassword"                    # \features\steps.py:298
    Then I should receive an error message                               # \features\steps.py:311

Feature: View selected user profile                                                            # \features\ID010_View_Selected_User_Profile.feature:1
  As a user of the "We're Board" app, I would like to be able to access another user's profile # \features\ID010_View_Selected_User_Profile.feature:3
  so I can decide whether or not to interact with this user                                    # \features\ID010_View_Selected_User_Profile.feature:4

  Background:

5 features (5 passed)
16 scenarios (16 passed)
58 steps (58 passed)

C:\Users\jawk\OneDrive\Documents\GitHub\we-re-board-backend\tests>pause
Press any key to continue . . .